
services:

  # Backend
  backend:
    build:
      context: ./Site.Server
      dockerfile: Dockerfile
    container_name: gotcloth-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"
    networks:
      - gotcloth-network
    restart: unless-stopped
    volumes:
      - ./Site.Server/wwwroot/images:/app/wwwroot/images

  # Frontend
  frontend:
    build:
      context: ./site.client
      dockerfile: Dockerfile
    container_name: gotcloth-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - gotcloth-network
    restart: unless-stopped

networks:
  gotcloth-network:
    driver: bridge
