server {
    # Listen on port 80
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Cache static assets
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
    
    # Proxy API calls to backend
    location /api/ {
        proxy_pass http://backend:80/; # Backend is the name of the backend service in docker-compose.yml
        proxy_set_header Host $host; # Set the host header to the host of the request
        proxy_set_header X-Real-IP $remote_addr; # Set the real IP address of the client
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # Set the forwarded for header to the proxy address
        proxy_set_header X-Forwarded-Proto $scheme; # Set the forwarded protocol to the scheme of the request
    }


    # Proxy other backend endpoints
    location ~ ^/(AddToCart|GetCart|PatchCart|RemoveProduct|FilterCart|payment|appendTotal|getTotal|Images|Product|weatherforecast) {
        proxy_pass http://backend:80; # Backend is the name of the backend service in docker-compose.yml
        proxy_set_header Host $host; # Set the host header to the host of the request
        proxy_set_header X-Real-IP $remote_addr; # Set the real IP address of the client
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # Set the forwarded for header to the proxy address
        proxy_set_header X-Forwarded-Proto $scheme; # Set the forwarded protocol to the scheme of the request
    }

    # Serve index.html for all routes
    # Routes as in /products, /cart, /login, etc.
    location / {
        try_files $uri $uri/ /index.html;
    }

}